import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

import pkg from '../package.json' with { type: 'json' };
import { basePackageExports } from '../packageExports';

const scriptDir = import.meta.dirname;
const packageRoot = path.resolve(scriptDir, '..');

type ComponentExport = {
  exportName: string;
  exportPath: string;
  sourcePath: string;
  componentNames: string[];
};

function toPosixPath(value: string) {
  return value.replaceAll(path.sep, '/');
}

function withDotSlash(value: string) {
  const posixPath = toPosixPath(value);
  return posixPath.startsWith('.') ? posixPath : `./${posixPath}`;
}

async function scanComponentExports() {
  const glob = new Bun.Glob('./src/components/**/index.ts');

  const files = glob.scanSync({
    cwd: packageRoot,
    absolute: true,
  });

  const result: ComponentExport[] = [];

  for (const indexFile of files) {
    const mod = (await import(pathToFileURL(indexFile).href)) as Record<string, unknown>;

    const sourcePath = withDotSlash(path.relative(packageRoot, indexFile));
    const exportPath = sourcePath.replace(/^\.\/src\//, './').replace(/\/index\.ts$/, '');
    const exportName = exportPath.slice(2);

    const componentNames = Object.entries(mod)
      .filter(([, value]) => typeof value === 'string' && value.endsWith('.vue'))
      .map(([name]) => name);

    if (componentNames.length === 0) continue;

    result.push({
      exportName,
      exportPath,
      sourcePath,
      componentNames,
    });
  }

  return result;
}

function updatePackageExports(items: ComponentExport[]) {
  const packageJsonPath = path.resolve(packageRoot, './package.json');
  const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf-8'));

  packageJson.exports = { ...basePackageExports };
  const shortItems = items.sort((a, b) => a.exportPath.localeCompare(b.exportPath));

  for (const item of shortItems) {
    packageJson.exports[item.exportPath] = item.sourcePath;
  }

  fs.writeFileSync(packageJsonPath, `${JSON.stringify(packageJson, null, 2)}\n`);
}

function generateComponentResolverJson(items: ComponentExport[]) {
  const jsonPath = path.resolve(packageRoot, 'nuxt', 'components.json');

  const resolverMap = Object.fromEntries(
    items
      .flatMap(item =>
        item.componentNames.map(
          componentName => [componentName, `${pkg.name}/${item.exportName}`] as const,
        ),
      )
      .sort(([nameA], [nameB]) => nameA.localeCompare(nameB)),
  );

  fs.writeFileSync(jsonPath, `${JSON.stringify(resolverMap, null, 2)}\n`);
}

function generateType(items: ComponentExport[]) {
  const content = items
    .flatMap(item =>
      item.componentNames.map(componentName => ({
        componentName,
        line: `    ${componentName}: typeof import('${pkg.name}/${item.exportName}')['${componentName}']`,
      })),
    )
    .sort((a, b) => a.componentName.localeCompare(b.componentName))
    .map(item => item.line)
    .join('\n');

  const code = `/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
${content}
  }
}
`;

  fs.writeFileSync(path.join(packageRoot, './types.d.ts'), code);
}

async function generate() {
  const items = await scanComponentExports();

  updatePackageExports(items);
  generateComponentResolverJson(items);
  generateType(items);

  console.log(`Generated ${items.length} component entries.`);
}

generate();
