name: guard-plus

services:
  guard-plus-db-test:
    image: postgres:18-alpine
    container_name: gp-db-test
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: guard_plus
      POSTGRES_DB: guard-plus-test
    ports:
      - '8799:5432'
    volumes:
      - guard-plus-db-test-data:/var/lib/postgresql

  guard-plus-redis-test:
    image: redis:8-alpine
    container_name: gp-redis-test
    restart: unless-stopped
    ports:
      - '8798:6379'

volumes:
  guard-plus-db-test-data:
