name: guard-plus-app

x-logging: &logging
  driver: local
  options:
    max-size: 20m
    max-file: 10

services:
  user-web:
    container_name: user-web

    build:
      context: ../../
      dockerfile: webs/user/Dockerfile
      target: user-web

    restart: unless-stopped

    logging: *logging

    env_file:
      - .env.prod

    environment:
      NODE_ENV: production
      NITRO_PRESET: bun
      HOST: 0.0.0.0
      PORT: 3000

    ports:
      - target: 3000
        published: 3996
        protocol: tcp
        host_ip: 0.0.0.0
